name: Prompt Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-prompts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            echo "Lockfile detected — running npm ci"
            npm ci --no-audit --no-fund
          else
            echo "No lockfile — running npm install"
            npm install --no-audit --no-fund
          fi

      - name: Run prompt tests
        run: npm test
